# Generated by Django 3.2.23 on 2023-12-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='game_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.game', verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='gamer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='vishlist',
            field=models.CharField(blank=True, max_length=200, verbose_name='Список пожеланий'),
        ),
    ]
