# Generated by Django 3.2.23 on 2023-12-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_auto_20231216_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='game_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamers', to='telegram_bot.game', verbose_name='Название игры'),
        ),
    ]
