# Generated by Django 3.2.23 on 2023-12-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_game_drawing_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_ranges',
            field=models.ManyToManyField(blank=True, to='telegram_bot.PriceRange', verbose_name='Диапазон цены'),
        ),
    ]
